// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Choice } from "./Choice";
import type { EndedBy } from "./EndedBy";

/**
 * A question an agent asked and then moved past. Not answerable: the tool call
 * is over, so the type has nowhere to put an answer.
 */
export type AbandonedQuestion = { 
/**
 * As the agent wrote it. Rendered, never summarised.
 */
question: string, 
/**
 * The options it offered, so a person can see what it chose between.
 */
options?: Array<Choice>, asked_at: string, abandoned_at: string, 
/**
 * What the agent did instead, where that is the next thing it did.
 */
moved_on_to?: string | null, ended_by: EndedBy, };
