// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Choice } from "./Choice";

/**
 * A question an agent asked and then moved past.
 *
 * **Not answerable, and the type says so by having nowhere to put an answer.**
 * The tool call is over; offering a button would be offering something no
 * route can deliver, which is the defect the driven ask was built to avoid and
 * would be a worse version of here.
 */
export type AbandonedQuestion = { 
/**
 * As the agent wrote it. Rendered, never summarised.
 */
question: string, 
/**
 * The options it offered, so a person can see what it chose between.
 */
options?: Array<Choice>, asked_at: string, abandoned_at: string, 
/**
 * What the agent did instead, where that is the next thing it did.
 */
moved_on_to?: string | null, };
