// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How long a question waits before the clock answers it.
 *
 * **Zero is a different fact, not a small number.** `CLAUDE_AFK_TIMEOUT_MS=0`
 * *"doesn't turn the timeout off; it closes the dialog immediately"* — every
 * question in that session ended by nobody the instant it is asked. Rendering
 * that as `after 0s` is arithmetic where a sentence is owed, so the type
 * refuses to let a surface do it.
 */
export type After = "immediately" | { "idle": string } | "never";
