// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How long a question waits before the clock answers it. `Immediately` is its
 * own variant: `CLAUDE_AFK_TIMEOUT_MS=0` closes the dialog at once, which a
 * surface must say in words, not as `after 0s`.
 */
export type After = "immediately" | { "idle": string } | "never";
