// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AskDeadline } from "./AskDeadline";
import type { AskDelivery } from "./AskDelivery";
import type { AskEnded } from "./AskEnded";
import type { AskId } from "./AskId";
import type { AskKind } from "./AskKind";
import type { ProjectId } from "./ProjectId";
import type { RunId } from "./RunId";

/**
 * One thing an agent asked a person, and everything that became of it. The id
 * is an opaque token a person answers by from any surface at any later time —
 * never the session, which may be gone.
 */
export type Ask = { id: AskId, kind: AskKind, run: RunId, project: ProjectId | null, 
/**
 * The protocol's in-flight request id; only meaningful while its connection
 * lives, which is why it is not the key.
 */
request_id: string, 
/**
 * What the agent asked, as the agent wrote it.
 */
message: string, 
/**
 * The options and form, untouched. `unknown` on the wire: it is the agent's
 * own schema, not ours to type.
 */
payload: unknown, asked_at: string, deadline: AskDeadline, 
/**
 * What the person chose, written **before** anything is delivered.
 */
answer?: unknown | null, answered_at?: string | null, 
/**
 * Which surface answered — `cli`, `board`, `mcp`.
 */
answered_from?: string | null, delivery?: AskDelivery | null, ended?: AskEnded | null, ended_at?: string | null, };
