// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether the person's answer reached the agent, and how.
 *
 * **Recorded separately from the answer itself, because they are different
 * facts and the gap between them is the whole feature.** An answer written
 * down at 09:00 and delivered at 14:00 to a resumed session is a success; an
 * answer written down and never delivered is a different thing entirely, and
 * collapsing the two would let this product claim a delivery it never made.
 */
export type AskDelivery = "live" | "resumed" | { "undeliverable": { because: string, } };
