// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether the person's answer reached the agent, and how.
 *
 * Whether the person's answer reached the agent, and how. Kept separate from
 * the answer: recorded-but-undelivered must never read as delivered.
 */
export type AskDelivery = "live" | "resumed" | { "undeliverable": { because: string, } };
