// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How long an unanswered ask may wait. `Never` is the default, deliberately:
 * a question must not end on a clock its owner did not choose. A project that
 * sets a bound gets a row naming the duration and the file it came from.
 */
export type AskDeadline = "never" | { "after": number };
