// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How long an unanswered ask may wait.
 *
 * **`Never` is the default and is not a placeholder.** It is what the agent's
 * own vendor does, it is what a terminal does when it shows a dialog and
 * nobody is at the desk, and it is the only setting under which this product's
 * argument survives contact with its own code: a question that ends on a clock
 * nobody chose is the thing [`DIRECTION`](https://hupe1980.github.io/devplane)
 * §1 indicts four vendors for.
 *
 * A project that wants a bound sets one, and then the row that ends the ask
 * names the duration **and the file it came from**, because *a timer* without
 * *whose timer* is the same non-answer as *the daemon decided*.
 */
export type AskDeadline = "never" | { "after": number };
