// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How an ask stopped waiting, and on whose authority.
 */
export type AskEnded = "person" | "stopped" | { "timer": { after: number, set_by: string, } } | { "nobody": { because: string, } };
