// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How an ask stopped waiting, and on whose authority.
 *
 * **Three, and the third is the one the product is named for.** Every system
 * that lets a request expire has the first two; the row that says *nobody
 * decided this and here is what was asked* is the one nothing else writes.
 */
export type AskEnded = "person" | { "timer": { after: number, set_by: string, } } | { "nobody": { because: string, } };
