// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 *One thing an agent asked a person. **An opaque token, and that is the point**: it is what an answer is addressed to, from any surface, however long afterwards and whatever process is alive by then. Addressing an answer by session is what made an answer undeliverable the moment the session was gone.
 */
export type AskId = string;
