// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What was asked: a **permission** (is this action allowed — `session/request_permission`,
 * which policy can answer) or a **question** (which thing does the person want —
 * `elicitation/create`, which no rule can answer). Decides how it is answered, never how it waits.
 */
export type AskKind = "permission" | "question";
