// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of thing was asked, which decides how it is answered and never how
 * it waits.
 *
 * Not a shade of the same thing: a **permission** asks whether an action is
 * allowed, so a grant or a refusal is what the options mean however the agent
 * spells them; a
 * **question** asks which of several things the person wants, and no rule can
 * answer it. They arrive on different protocol channels — `session/request_permission`
 * and `elicitation/create` — and only one of them has a policy.
 */
export type AskKind = "permission" | "question";
