// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * **On whose authority something happened.**
 *
 * This is the column the product is named for, and for five passes it could
 * not say what the design required. It had three values — `policy`, `human`,
 * `daemon` — and *daemon* was doing three unrelated jobs at once: Devplane
 * running a gate, a clock refusing a call nobody answered, and a question
 * dying unanswered when its run ended. The reason string told those apart and
 * the queryable column did not, in the one table whose whole purpose is being
 * queried by exactly that dimension.
 *
 * # Why these five and not six
 *
 * `classifier` is deliberately absent, and its absence is a measurement
 * rather than an oversight. Devplane has no channel that attributes an
 * individual call to a model's approval: across four concurrent sessions,
 * `PreToolUse` fired forty-nine times and `PermissionRequest` fired **zero**
 * times, so a call in an `auto` session is one nobody was asked about — which
 * is a fact about the *session's mode*, reported by `devplane modes`, and not
 * a fact about the call. A variant nothing can produce is a documented
 * trigger with no code behind it.
 *
 * `unknown` is absent for the stronger reason: a row whose authority cannot be
 * established is not a row with another kind of authority, it is **a row
 * Devplane must not write**. A ledger that guesses is worse than one with
 * gaps.
 */
export type Authority = "person" | "rule" | "timer" | "nobody" | "daemon";
