// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BatchId } from "./BatchId";
import type { BatchKind } from "./BatchKind";
import type { Position } from "./Position";
import type { PreflightFinding } from "./PreflightFinding";

/**
 * One person's intent, sent once.
 */
export type Batch = { id: BatchId, 
/**
 * Stored once, not per member.
 */
prompt: string, 
/**
 * The library artefact it started from, when it did.
 */
template?: string | null, position: Position, kind: BatchKind, sent_at: string, 
/**
 * The dispatch authority: who sent it. One authority for the batch, and
 * one per run — *you approved the plan* and *a rule allowed what it then
 * did* are different facts about the same afternoon.
 */
sent_by: string, 
/**
 * **Every project chosen, including the ones the preflight refused.** A
 * record that dropped them would answer *what did I send this to* with the
 * subset that happened to work.
 */
targets: Array<PreflightFinding>, };
