// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 *One person's intent, sent once, to many targets. The reviewable unit of a fan-out: six runs from one prompt are not six things to review, they are one thing that happened six times.
 */
export type BatchId = string;
