// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of thing this batch is.
 *
 * **Two kinds, not a nullable member list**, and the distinction is
 * load-bearing. Modelling a draft as *a dispatched batch whose members have
 * not arrived* would make a draft nobody sent indistinguishable from six runs
 * that failed to start — which is exactly the collapse this feature exists to
 * prevent.
 */
export type BatchKind = "drafted" | "dispatched";
