// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a change has got to, computed by [`Change::state`]; never stored.
 * Every surface reads the word and glyph from here.
 */
export type ChangeState = "drafted" | "isolated" | "in flight" | "verified" | "offered" | "archived";
