// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One answer a blocked run will accept. The label is for humans; the `id` is
 * what the protocol requires back — ACP option ids are the agent's to choose.
 */
export type Choice = { 
/**
 * The protocol's id for this option. Absent for an observed session,
 * whose dialog belongs to the provider and cannot be answered from here.
 */
id: string | null, label: string, 
/**
 * `allow_once`, `allow_always`, `reject_once`, `reject_always` where the
 * protocol says so.
 */
kind: string | null, };
