// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Position } from "./Position";

/**
 * The position a fan-out starts at, and whether the count chose it.
 *
 * `forced` exists so a surface can say *draft was selected for you* rather
 * than letting somebody discover that their choice was overridden. A default
 * nobody is told about is a decision taken on their behalf, which is the
 * thing this product exists to make visible.
 */
export type Chosen = { position: Position, forced: boolean, };
