// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who set it. *You chose this* and *somebody chose this for you* are different
 * facts about the same duration.
 */
export type ClockSource = "user" | "managed" | "environment";
