// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which file set it.
 *
 * **`Managed` is the interesting one**, and it is the reason this enum exists
 * rather than a bare `Option<String>`: *you chose this* and *somebody else
 * chose this for you* are different facts about the same duration.
 */
export type ClockSource = "user" | "managed";
