// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClockSource } from "./ClockSource";

/**
 * One clock as a surface reads it: the sentence is composed here so the CLI,
 * the board and `--json` render words, not ingredients.
 */
export type ClockLine = { 
/**
 * The duration as a person would say it, or `immediately`.
 */
after: string, 
/**
 * Whether questions close with no wait. A flag, not a string compare on
 * `after`, so a rename cannot silently disable it.
 */
immediate: boolean, source: ClockSource, where_set: string, 
/**
 * The whole sentence, which is what a surface prints.
 */
says: string, chosen_by_the_person: boolean, 
/**
 * Whether this clock answers for the person; `false` only for `never`.
 * A flag for the same reason as `immediate`.
 */
answers_for_you: boolean, };
