// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who set it, and it is not always a file.
 *
 * **The enum exists because *you chose this* and *somebody else chose this for
 * you* are different facts about the same duration** — and a bare
 * `Option<String>` cannot tell them apart. `Managed` was the interesting one
 * until `Environment` was added, and `Environment` is now the dangerous one:
 * it outranks both files and turns the timer on where they say `never`.
 */
export type ClockSource = "user" | "managed" | "environment";
