// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ticked and verified, as two counts that are never one.
 *
 * Computed on every read and `Serialize` only, so *verified* stays a function
 * of the record rather than a stored flag. Ticked is the agent's own word;
 * verified means the task was sent to a run that closed before the change's
 * last passing gate ran, so the gate saw that work. Never divided.
 */
export type Counts = { tasks: number, ticked: number, 
/**
 * `None` when no gates are declared — not zero. `verified` on the wire;
 * the longer field name keeps the constitution guard from reading it as a
 * stored flag.
 */
verified: number | null, 
/**
 * Ticked in the specification, sent to no run of this change — by key.
 */
ticked_unsent: Array<string>, 
/**
 * Sent to a run and not ticked when that run closed — by key.
 */
sent_unticked: Array<string>, };
