// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ticked, and seen by a passing check, as two counts that are never one.
 *
 * Ticked is the agent's own word. *Seen by a passing check* means the task was
 * sent to a run that closed before a `check` that passed, so that check ran
 * over its work. It is never called *verified*: the check may have failed
 * since, and only the change is ever verified. Computed on every read and
 * `Serialize` only. Never divided.
 */
export type Counts = { tasks: number, ticked: number, 
/**
 * `None` when no gates are declared — not zero.
 */
seen_by_pass: number | null, 
/**
 * Ticked in the specification, sent to no run of this change — by key.
 */
ticked_unsent: Array<string>, 
/**
 * Sent to a run and not ticked when that run closed — by key.
 */
sent_unticked: Array<string>, };
