// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a declared test covers a path. *Not covered* is a finding; *no
 * mapping* is the limit of what was declared, and must not render as either.
 */
export type Coverage = { "coverage": "covered", test: string, } | { "coverage": "not_covered" } | { "coverage": "no_mapping" };
