// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Authority } from "./Authority";
import type { ProjectId } from "./ProjectId";
import type { RunId } from "./RunId";
import type { WorkId } from "./WorkId";

/**
 * One thing that was decided.
 *
 * `action` is the verb, in the same vocabulary the policy speaks:
 * `agent:tool.use`, `gate:run`, `git:push`, `gh:pr.create`, `work:advance`.
 * `subject` is what it was about — the command, the gate, the branch.
 */
export type Decision = { id: string, at: string, authority: Authority, action: string, subject: string, 
/**
 * `allow`, `deny`, `pass`, `fail`, `done`.
 */
outcome: string, 
/**
 * The rule that decided, or the reason. This is the field the whole table
 * exists for: "auto-approved" is not an answer, "auto-approved by
 * `Bash(pnpm test *)`" is.
 */
reason: string | null, 
/**
 * The tool this call was, where it was a tool call at all.
 *
 * `Bash`, `Read`, `Edit`, `mcp__…`. Empty for a gate verdict, a push or a
 * pipeline advancing, which are decisions about something other than a
 * tool.
 */
tool: string | null, 
/**
 * Where the MCP server behind `tool` came from, as the vendor reported it.
 *
 * **The adjacent question to `authority`, and the reason this field is
 * here rather than on the event alone.** `authority` answers *on whose
 * authority was this decided*; this answers *what was acting, and who put
 * it there*. A call into a server a cloned repository defined and one into
 * a server the person installed themselves are different facts, and until
 * this field existed they produced identical rows.
 *
 * `None` for a tool that is not an MCP tool, for a vendor that reports no
 * such thing, and for an agent older than the release that began sending
 * it. Absent is not unknown.
 */
server_source: string | null, project_id: ProjectId | null, run_id: RunId | null, work_id: WorkId | null, };
