// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Authority } from "./Authority";
import type { ProjectId } from "./ProjectId";
import type { RunId } from "./RunId";
import type { WorkId } from "./WorkId";

/**
 * One thing that was decided.
 *
 * `action` is the verb, in the same vocabulary the policy speaks:
 * `agent:tool.use`, `gate:run`, `git:push`, `gh:pr.create`, `work:advance`.
 * `subject` is what it was about — the command, the gate, the branch.
 */
export type Decision = { id: string, at: string, authority: Authority, action: string, subject: string, 
/**
 * `allow`, `deny`, `pass`, `fail`, `done`.
 */
outcome: string, 
/**
 * The rule that decided, or the reason. This is the field the whole table
 * exists for: "auto-approved" is not an answer, "auto-approved by
 * `Bash(pnpm test *)`" is.
 */
reason: string | null, 
/**
 * The tool this call was, where it was a tool call at all.
 *
 * `Bash`, `Read`, `Edit`, `mcp__…`. Empty for a gate verdict, a push or a
 * pipeline advancing, which are decisions about something other than a
 * tool.
 */
tool: string | null, project_id: ProjectId | null, run_id: RunId | null, work_id: WorkId | null, };
