// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Authority } from "./Authority";
import type { ChangeId } from "./ChangeId";
import type { ProjectId } from "./ProjectId";
import type { RunId } from "./RunId";

/**
 * One thing that was decided. `action` is the verb in the policy's vocabulary
 * (`agent:tool.use`, `gate:run`, `git:push`, `gh:pr.create`, `change:stop`);
 * `subject` is what it was about.
 */
export type Decision = { id: string, at: string, authority: Authority, action: string, subject: string, 
/**
 * `allow`, `deny`, `pass`, `fail`, `done`.
 */
outcome: string, 
/**
 * The rule that decided, or the reason: "auto-approved by
 * `Bash(pnpm test *)`", not "auto-approved".
 */
reason: string | null, 
/**
 * The tool, for a tool call (`Bash`, `Edit`, `mcp__…`); `None` otherwise.
 */
tool: string | null, 
/**
 * Where the MCP server behind `tool` came from, as the vendor reported it:
 * *what was acting, and who put it there*, beside `authority`. `None` for
 * non-MCP tools and vendors or versions that do not report it — absent is
 * not unknown.
 */
server_source: string | null, project_id: ProjectId | null, run_id: RunId | null, change_id: ChangeId | null, };
