// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What happened to one copy, relative to the library.
 *
 * **The single most likely thing to be quietly reduced to a boolean.** Six
 * values because there are six situations, and collapsing any pair loses the
 * one fact a person needs: *which side moved*. `CopyMoved` and `LibraryMoved`
 * are the same boolean and opposite instructions.
 */
export type Drift = "unchanged" | "copy_moved" | "library_moved" | "both_moved" | "missing" | "unrecorded";
