// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a question came to be abandoned: derived from hook events, or asserted
 * by the vendor.
 */
export type EndedBy = "moved_on" | "session_ended" | "vendor_rejected";
