// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a gate run in a repository amounts to, for callers outside this
 * process. Four values so *no gates* and *unreadable config* never collapse
 * into *verified* or *failed*.
 */
export type GateState = "verified" | "failed" | "no_gates" | "config_unreadable";
