// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a gate run in a repository amounts to.
 *
 * **Four values, because there are four situations and `passed: bool` carries
 * two of them.** *The checks failed*, *this repository declares no checks* and
 * *this repository's configuration could not be read* are three different
 * sentences, and only the first is a failing gate. Collapsing them is how a
 * repository with no gates comes to look verified, or a broken configuration
 * comes to look like a red suite.
 *
 * It exists because something outside this process reads the answer — a Spec
 * Kit workflow asks an agent to run the gate and report it — and a caller that
 * sees `false` cannot tell *nothing was checked* from *the checks said no*.
 */
export type GateState = "verified" | "failed" | "no_gates" | "config_unreadable";
