// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a narrowing left out — counted, never implied.
 */
export type Narrowed = { 
/**
 * How many items the narrowing removed.
 */
count: number, 
/**
 * The projects those items belonged to.
 */
projects: Array<string>, 
/**
 * A project was asked for and matched nothing — distinct from that
 * project having nothing waiting.
 */
no_such_project: boolean, };
