// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a narrowing left out.
 *
 * **Counted rather than implied.** A list that silently shows a subset of what
 * needs you is the one failure this surface cannot take: the product is sold
 * on *one page for everything*, and a page that quietly became a filter has
 * broken that promise without saying so.
 */
export type Narrowed = { 
/**
 * How many items the narrowing removed.
 */
count: number, 
/**
 * The projects those items belonged to, named, so the sentence can be
 * *4 elsewhere, in saas and payments-api* rather than a bare number.
 */
projects: Array<string>, 
/**
 * Whether a project was asked for and matched nothing — which is a
 * different fact from *that project has nothing waiting*, and the two read
 * identically unless something says so.
 */
no_such_project: boolean, };
