// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunId } from "./RunId";

/**
 * Why a changed file sits under *not asked for*.
 */
export type NotAskedFor = { "why": "no_run_wrote" } | { "why": "run_sent_no_tasks", run: RunId, };
