// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Heading } from "./Heading";
import type { Progress } from "./Progress";
import type { Question } from "./Question";

/**
 * A specification as a surface needs it: the outline, how far it has moved,
 * and what it says it has not answered.
 *
 * **Composed here rather than by each caller**, because the two counts on it
 * are also the two the done certificate stamps, and a second place deriving
 * them is a second place to get the `checklists/` rule or the `tasks.md` rule
 * wrong. `SpecStamp` and this both read one [`Spec`]; a test asserts they
 * agree for one folder at one commit.
 */
export type Plan = { 
/**
 * As the work named it, relative to the project root.
 */
path: string, 
/**
 * **False when the work names a specification that is not there**, which
 * is a finding rather than a blank — the certificate has recorded it since
 * the certificate shipped, and nothing has ever shown it.
 */
present: boolean, 
/**
 * How many markdown documents it covers.
 */
files: number, 
/**
 * `None` where there is no task list. See [`Progress`].
 */
progress: Progress | null, 
/**
 * **Which bound this reading hit**, where it hit one.
 *
 * The walk stops at three levels and the question lines are capped. A
 * caller that reaches either gets a shorter answer, and a shorter answer
 * that does not say it is short is a figure nobody can check. `None` means
 * the whole specification was read.
 */
truncated: string | null, 
/**
 * Bounded, because a folder can carry any number and a ranked inbox may
 * not be flooded by one project. The count is on [`Self::open_questions`].
 */
questions: Array<Question>, open_questions: number, 
/**
 * The headings, in path order. No tool's section names are recognised.
 */
outline: Array<Heading>, 
/**
 * Of every document under the folder. `None` when there is nothing to
 * fingerprint.
 */
fingerprint: string | null, };
