// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Heading } from "./Heading";
import type { Progress } from "./Progress";
import type { Question } from "./Question";

/**
 * A specification as a surface needs it: outline, progress, open questions.
 * Composed here, from the same [`Spec`] as `SpecStamp`, so the certificate and
 * the surfaces cannot count differently.
 */
export type Plan = { 
/**
 * As the change named it, relative to the project root.
 */
path: string, 
/**
 * False when the named specification is not there — a finding.
 */
present: boolean, 
/**
 * How many markdown documents it covers.
 */
files: number, 
/**
 * `None` where there is no task list.
 */
progress: Progress | null, 
/**
 * Which bound this reading hit, if any; `None` means all of it was read.
 */
truncated: string | null, 
/**
 * Bounded; the full count is [`Self::open_questions`].
 */
questions: Array<Question>, open_questions: number, 
/**
 * The headings, in reading order.
 */
outline: Array<Heading>, fingerprint: string | null, };
