// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Why } from "./Why";

/**
 * One documented failure, for one field.
 */
export type PortabilityFinding = { field: string, why: Why, };
