// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortabilityFinding } from "./PortabilityFinding";

/**
 * What a report can say about one artefact's frontmatter.
 */
export type Portability = { findings: Array<PortabilityFinding>, 
/**
 * **Set when the frontmatter could not be parsed at all**, so that an
 * empty finding list never reads as *nothing will be lost*.
 *
 * The distinction is the whole reason this field exists: *no findings* and
 * *not read* are the same output and opposite facts.
 */
unread: boolean, };
