// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How far a fan-out may go without you.
 *
 * **Per dispatch, never a global setting.** A dial somebody set once and
 * forgot is a dial that decides things nobody is thinking about; this is
 * chosen for each fan-out, with the number of targets in front of the person
 * choosing.
 */
export type Position = "draft" | "to_gate" | "to_pull_request";
