// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why one project cannot take *this* change.
 */
export type PreflightReason = "unknown_project" | "untrusted" | "config_will_not_load" | "no_such_agent" | "dirty_worktree" | "cannot_send";
