// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreflightNote } from "./PreflightNote";
import type { PreflightReason } from "./PreflightReason";

/**
 * One project and what the preflight said about it. A snapshot: the start
 * checks again.
 */
export type PreflightFinding = { 
/**
 * What the person asked for: a name, an id or a path.
 */
asked: string, 
/**
 * The registered project's name, or the directory's where none is.
 */
name: string, 
/**
 * The repository root, when the name resolved to one.
 */
root: string | null, refusal: PreflightReason | null, 
/**
 * The refusal as one line with its fix.
 */
says: string | null, 
/**
 * What the first run in a fresh tree will cost. Never sets `refusal`.
 */
notes?: Array<PreflightNote>, };
