// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What will happen in the fresh tree, said before anything starts. Advisory,
 * never a refusal.
 */
export type PreflightNote = { "note": "first_run_installs", command: string, } | { "note": "no_setup_declared", lockfiles: Array<string>, };
