// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why one target cannot take *this* dispatch.
 */
export type PreflightReason = "untrusted" | "dirty_worktree" | "no_such_agent" | "config_will_not_load" | "over_ceiling";
