// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreflightReason } from "./PreflightReason";
import type { ProjectId } from "./ProjectId";

/**
 * One target and what the preflight said about it, with the time it was said.
 *
 * **A snapshot, not a promise.** A target can become undispatchable between
 * the preflight and the send — somebody commits, somebody edits a config — so
 * the time is carried and a surface says *as of* rather than implying a
 * guarantee it cannot make.
 */
export type PreflightFinding = { project: ProjectId, refusal: PreflightReason | null, 
/**
 * Fields this target's vendor would reject, from the library's portability
 * report. **A warning and never a refusal**: the artefact still works in
 * the tool that wrote it, and the documented error is about leaving it.
 */
would_lose_fields?: Array<string>, at: string, };
