// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How far a task list has moved, when there **is** one.
 *
 * **`0 of 0` is unrepresentable, and that is the whole reason this is a type.**
 * A specification with no task list is not a specification with no progress: a
 * full bar over a plan that has no boxes is the most confident wrong thing a
 * surface can say, and rendering it was one component away for as long as the
 * counts travelled as two bare integers. A caller receives `None` and has
 * nothing to divide.
 */
export type Progress = { done: number, 
/**
 * Always greater than zero. A [`Progress`] only exists where boxes do.
 */
total: number, };
