// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How far a task list has moved. `0 of 0` is unrepresentable: with no boxes a
 * caller gets `None`, never a full or empty bar.
 */
export type Progress = { done: number, 
/**
 * Always greater than zero.
 */
total: number, };
