// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The rows a change's diff weakened, counted by kind, with how many no person
 * has marked seen. Beside *verified* on every surface; derived from the same
 * rows the review's first group shows, so the two cannot disagree.
 */
export type Qualifier = { 
/**
 * Rows of kind [`WeakKind::Skip`].
 */
weakened: number, 
/**
 * Rows of kind [`WeakKind::Deleted`].
 */
deleted: number, 
/**
 * Rows of kind [`WeakKind::Gate`].
 */
gates_changed: number, 
/**
 * Rows with no current seen mark.
 */
unseen: number, 
/**
 * *1 check weakened · 1 gate changed*, or empty when nothing was.
 */
says: string, };
