// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClockSource } from "./ClockSource";

/**
 * What can answer a question on this machine without the person.
 */
export type QuestionClock = { 
/**
 * The duration, in the vendor's own spelling — `60s`, `5m`, `10m`.
 */
after: string, source: ClockSource, 
/**
 * The file it came from, so a person can go and look at it.
 */
file: string, };
