// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One unresolved question, with the document it is in.
 */
export type Question = { 
/**
 * Relative to the project root.
 */
path: string, 
/**
 * The line, in the project's own words.
 */
text: string, };
