// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { After } from "./After";
import type { ClockSource } from "./ClockSource";

/**
 * What can answer a question on this machine without the person.
 */
export type QuestionClock = { after: After, source: ClockSource, 
/**
 * **Where to go and change it** — a settings path for the two files, the
 * variable's name for the environment. One meaning, two shapes, which is
 * what a person actually needs; it was `file`, and a field called `file`
 * holding a variable name is a field with two meanings.
 */
where_set: string, };
