// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { After } from "./After";
import type { ClockSource } from "./ClockSource";

/**
 * What can answer a question on this machine without the person.
 */
export type QuestionClock = { after: After, source: ClockSource, 
/**
 * Where to change it: a settings path, or the variable's name.
 */
where_set: string, };
