// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Qualifier } from "./Qualifier";

/**
 * What the review of a change *ready to decide* would lead with, carried on
 * its inbox row so the row never reads as calmer than the review. Hunks seen
 * are the window's own marks, so the host sends only the total.
 */
export type ReadyFacts = { qualifier: Qualifier, 
/**
 * Every hunk in the change.
 */
hunks: number, 
/**
 * Files no declared test covers; `None` when no mapping is declared.
 */
not_covered: number | null, 
/**
 * Hunks in files no dispatched task asked for; `None` when grouping by
 * task is unavailable.
 */
not_asked_for: number | null, 
/**
 * The two counts in words, or why each is unknown: *1 file covered by
 * nothing*, *no test mapping declared*.
 */
says: Array<string>, };
