// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectId } from "./ProjectId";

export type ReportTarget = { "to": "project", project: ProjectId, name: string, } | { "to": "github", repo: string, } | { "to": "source" };
