// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 *A finding one project filed about another. Minted `rp-…` when it is filed, so it reads as what it is wherever it is pasted.
 */
export type ReportId = string;
