// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeId } from "./ChangeId";
import type { ProjectId } from "./ProjectId";
import type { ReportFiler } from "./ReportFiler";
import type { RunId } from "./RunId";

/**
 * Where a report came from, as the host resolved it: nothing the filer types
 * reaches these fields. The private seal keeps the two constructors the only
 * way to build one.
 */
export type ReportProvenance = { project: ProjectId, project_name: string, 
/**
 * `None` for a run that belongs to no change.
 */
change: ChangeId | null, run: RunId | null, agent: string | null, by: ReportFiler, at: string, };
