// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the finding rests on: bounded, cited rather than transcribed.
 */
export type ReportEvidence = { command: string | null, output: string | null, stack: string | null, 
/**
 * `a..b`, two object names.
 */
commits: string | null, 
/**
 * Each confined to the source project or its change's worktree.
 */
paths: Array<string>, };
