// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeId } from "./ChangeId";
import type { ReportEvidence } from "./ReportEvidence";
import type { ReportId } from "./ReportId";
import type { ReportKind } from "./ReportKind";
import type { ReportProvenance } from "./ReportProvenance";
import type { ReportState } from "./ReportState";
import type { ReportTarget } from "./ReportTarget";

export type Report = { id: ReportId, kind: ReportKind, title: string, finding: string, evidence: ReportEvidence, target: ReportTarget, provenance: ReportProvenance, state: ReportState, resolved_at: string | null, 
/**
 * Changes whose runs were handed the resolution, so it is told once.
 */
told: Array<ChangeId>, };
