// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeId } from "./ChangeId";

export type ReportState = { "state": "open" } | { "state": "accepted", change: ChangeId, } | { "state": "fixed", change: ChangeId | null, reason: string | null, } | { "state": "rejected", reason: string, } | { "state": "deferred", reason: string, } | { "state": "drafted" } | { "state": "opened", url: string, } | { "state": "discarded" };
