// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the filer says this is; never inferred, no triage, no severity.
 */
export type ReportKind = "defect" | "request" | "question" | "breaking_change";
