// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who filed it: an agent the host could name a run for, or a person.
 */
export type ReportFiler = "agent" | "person";
