// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where being wrong is expensive, most expensive first. The order is fixed;
 * which paths are which is declared in `[review.roles]`.
 */
export type ReviewRole = "shared" | "logic" | "security" | "integration" | "wiring" | "tests";
