// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 *A Devplane run. For observed sessions this mirrors the `SessionId`: a session we did not start has no other identity we can correlate on.
 */
export type RunId = string;
