// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One task sent to a run, as the run's record carries it.
 */
export type SentTask = { 
/**
 * The task file, relative to the project root.
 */
path: string, 
/**
 * The key — the line without its box.
 */
text: string, 
/**
 * The tokens the line cited when sent.
 */
cites: Array<string>, 
/**
 * Where it was when sent; for the editor link, never for identity.
 */
line: number, 
/**
 * Which occurrence of `text` in its file, from one; part of the identity.
 */
occurrence: number, };
