// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 *A provider's own session identifier — Claude Code's `session_id`, an ACP session id. Stable across resume, which is why runs are keyed by it.
 */
export type SessionId = string;
