// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewRole } from "./ReviewRole";

/**
 * How big a change is and where its weight sits, before anybody reads it.
 */
export type Shape = { files: number, added: number, removed: number, 
/**
 * Files per declared role, in role order; empty roles omitted.
 */
by_role: Array<[ReviewRole, number]>, formatter_only: number, not_read: number, 
/**
 * Whether roles were declared, so a count of none means none.
 */
ordered: boolean, };
