// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `.devplane.toml`, written beside an artefact Devplane never touches.
 *
 * **The two-file split is the whole trick**: the artefact stays byte-identical
 * to what its vendor expects, and the provenance lives next to it where `cat`
 * can read it. Putting this in SQLite would make the library's state invisible
 * to the editor that edits the library.
 *
 * Four facts and nothing else. There is no `safe`, no grade and no score, and
 * [`crate::core::setup`] is what answers *what will this be allowed to do*.
 */
export type Sidecar = { 
/**
 * Where it came from — `github:acme/skills#review-findings`, a path, a URL.
 */
origin: string, 
/**
 * The digest of what was fetched, so a later read can say whether the
 * thing on disk is still the thing that arrived.
 */
digest: string, 
/**
 * When, as RFC 3339.
 */
installed: string, 
/**
 * Who asked for it.
 */
by: string, };
