// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The specification moved under a run, and the run never saw it. Derived
 * from the run's close against the change's start; never stored.
 */
export type SpecDrift = { run: string, 
/**
 * When the newest document was written; `None` when the folder could
 * not be dated.
 */
changed_at: string | null, started_at: string, };
