// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a batch currently is.
 *
 * A pure function over its members, so the four empties are a test table
 * rather than four fixtures.
 */
export type State = "drafted" | "never_started" | "running" | "interrupted" | "finished";
