// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What one calendar day came to: counts, never a rate, trend or score, which
 * would measure the person.
 */
export type Tally = { 
/**
 * `by_person` through `by_nobody` are decisions taken on the person's
 * behalf; Devplane's own gates and bounds are counted apart.
 */
by_person: number, by_rule: number, by_timer: number, 
/**
 * Asked, never answered, and the moment passed.
 */
by_nobody: number, by_devplane: number, 
/**
 * Questions that waited for a person today: a count, never how long.
 */
questions_waited: number, };
