// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What one calendar day came to.
 *
 * **Counts, and no rate.** *You answered 4 of 17* is one word away from a
 * performance metric about the person; this names what happened and never how
 * well they did it. There is no percentage, no trend and no score.
 */
export type Tally = { 
/**
 * Decisions taken **on the person's behalf**, by authority.
 *
 * `daemon` is deliberately not in here: it is Devplane running a gate or
 * advancing a pipeline, which is the tool doing the job it was configured
 * to do rather than a decision taken for somebody. Folding the two
 * together would make the headline number a measure of how much the tool
 * did, which is the opposite of what this is for.
 */
by_person: number, by_rule: number, by_timer: number, 
/**
 * Asked, never answered, and the moment passed. **The row this product
 * exists to be able to write.**
 */
by_nobody: number, 
/**
 * What Devplane did mechanically, counted apart.
 */
by_daemon: number, 
/**
 * Questions that waited for a person at some point today.
 */
questions_waited: number, 
/**
 * The longest any one of them waited, in seconds.
 */
longest_wait_secs: bigint, };
