// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One requirement token's row: `REQ-3 · 3 tasks · 2 ticked · 0 verified`.
 */
export type TokenRow = { token: string, tasks: number, ticked: number, 
/**
 * `None` when no gates are declared; see [`Counts`].
 */
verified: number | null, };
