// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A digest over an artefact, and what the ignore list suppressed getting there.
 */
export type TreeDigest = { digest: string, 
/**
 * Relative paths the ignore list dropped, sorted.
 *
 * **Kept, and printed.** A suppressed difference that is not reported is
 * the ignore list turning into somewhere to hide a change.
 */
ignored: Array<string>, };
