// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One hunk or file that alters a check, with why. A signal from the diff
 * text alone, never a verdict: it says what it matched.
 */
export type Weakened = { path: string, why: string, };
