// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which kind of alteration a weakened row is. Counted by kind, never scored:
 * a skipped test and an edited CI workflow ask different questions.
 */
export type WeakKind = "skip" | "deleted" | "gate";
