// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WeakKind } from "./WeakKind";

/**
 * One hunk or file that alters a check, with why. A signal from the diff
 * text alone, never a verdict: it says what it matched.
 */
export type Weakened = { path: string, why: string, kind: WeakKind, 
/**
 * What it matched: the added or removed line, trimmed; the deleted path;
 * or, for an edit to a whole definition, a digest of its changed lines.
 * Part of a seen mark's key, so a different text is a different row.
 */
matched: string, };
