// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why one field will fail on those paths.
 */
export type Why = "unexpected_key" | "name_too_long" | "name_not_slug" | "description_too_long" | "compatibility_too_long";
