// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 *One unit of work: durable across sessions, and the thing a branch, a worktree and a set of gates belong to.
 */
export type WorkId = string;
