//! A block Devplane generated inside a file a person also edits.
//!
//! The format follows terraform-docs and doctoc: HTML-comment markers, only the
//! content between them is replaced, and missing markers are a refusal, never an
//! append — a person who deleted them chose not to have the block.

use std::ops::Range;

/// Keeps another tool's markers from ever matching.
const NS: &str = "devplane:";

/// A region of a co-authored file that Devplane owns.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedBlock {
    /// The block id, e.g. `gates` (written as `devplane:gates`).
    pub name: String,
    /// The generated content, without the markers or their newlines.
    pub body: String,
    /// Byte range of the whole block, markers included, in the host file.
    pub span: Range<usize>,
}

/// Why a block could not be read or written; each variant names the line at fault.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum MarkerError {
    /// The person removed the markers, or they were never there.
    #[error(
        "no `{NS}{name}` block found. Devplane does not append one: a file without the markers is \
         a file somebody chose not to have this block in. Add the markers back to restore it."
    )]
    Absent { name: String },

    /// Two blocks of one name; overwriting the first would be arbitrary.
    #[error("two `{NS}{name}` blocks, opening on lines {first} and {second}. Remove one.")]
    Duplicate {
        name: String,
        first: usize,
        second: usize,
    },

    /// Reading to end-of-file would swallow the person's content.
    #[error("`{NS}{name}` opens on line {line} and is never closed.")]
    Unterminated { name: String, line: usize },

    /// The body would truncate the block the next time it is read.
    #[error("the body for `{NS}{name}` contains the end marker, which would truncate the block.")]
    BodyContainsEnd { name: String },
}

/// Matched as a prefix, so the parser does not depend on the notice's wording.
fn begin_prefix(name: &str) -> String {
    format!("<!-- BEGIN {NS}{name}")
}

const NOTICE: &str = "· generated by Devplane; edits inside this block are overwritten";

fn begin(name: &str) -> String {
    format!("{} {NOTICE} -->", begin_prefix(name))
}

fn end(name: &str) -> String {
    format!("<!-- END {NS}{name} -->")
}

/// The block as it goes on disk. The body is normalised so rendering is
/// idempotent and an unchanged write produces an empty diff.
#[must_use]
pub fn render(name: &str, body: &str) -> String {
    let body = body.trim_end_matches('\n');
    if body.is_empty() {
        format!("{}\n{}", begin(name), end(name))
    } else {
        format!("{}\n{}\n{}", begin(name), body, end(name))
    }
}

/// Finds the one block of this name. A marker must be alone on its line; one
/// quoted mid-sentence is prose, not a marker.
///
/// # Errors
///
/// [`MarkerError::Duplicate`] and [`MarkerError::Unterminated`]. Absence is
/// `Ok(None)`; only writing to a missing block is a refusal.
pub fn find(text: &str, name: &str) -> Result<Option<GeneratedBlock>, MarkerError> {
    let (prefix, e) = (begin_prefix(name), end(name));
    let mut open: Option<(usize, usize)> = None; // (byte offset, line number)
    let mut found: Option<(GeneratedBlock, usize)> = None;
    let mut at = 0usize;

    for (i, line) in text.lines().enumerate() {
        let trimmed = line.trim();
        if trimmed.starts_with(&prefix) && trimmed.ends_with("-->") {
            if let Some((_, first)) = open {
                return Err(MarkerError::Duplicate {
                    name: name.into(),
                    first,
                    second: i + 1,
                });
            }
            open = Some((at, i + 1));
        } else if trimmed == e
            && let Some((start, line_no)) = open.take()
        {
            {
                let stop = at + line.len();
                // The body is everything between the two marker *lines*, so a
                // notice on the BEGIN line never leaks into it.
                let inner = &text[start..stop];
                let body = inner
                    .split_once('\n')
                    .map(|(_, rest)| rest)
                    .unwrap_or("")
                    .strip_suffix(&e)
                    .unwrap_or("")
                    .trim_matches('\n')
                    .to_string();
                if let Some((_, first)) = found {
                    return Err(MarkerError::Duplicate {
                        name: name.into(),
                        first,
                        second: line_no,
                    });
                }
                found = Some((
                    GeneratedBlock {
                        name: name.into(),
                        body,
                        span: start..stop,
                    },
                    line_no,
                ));
            }
        }
        // `lines()` strips the separator; every line here is followed by one.
        at += line.len() + 1;
    }

    if let Some((_, line)) = open {
        return Err(MarkerError::Unterminated {
            name: name.into(),
            line,
        });
    }
    Ok(found.map(|(b, _)| b))
}

/// Replaces the block's contents, leaving every other byte of the file alone.
///
/// # Errors
///
/// [`MarkerError::Absent`] (this never appends), whatever [`find`] reports, and
/// [`MarkerError::BodyContainsEnd`].
pub fn replace(text: &str, name: &str, body: &str) -> Result<String, MarkerError> {
    if body.contains(&end(name)) {
        return Err(MarkerError::BodyContainsEnd { name: name.into() });
    }
    let block = find(text, name)?.ok_or_else(|| MarkerError::Absent { name: name.into() })?;
    let mut out = String::with_capacity(text.len() + body.len());
    out.push_str(&text[..block.span.start]);
    out.push_str(&render(name, body));
    out.push_str(&text[block.span.end..]);
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    const GATES: &str = "run these:\n\n    cargo test";

    fn host(inner: &str) -> String {
        format!("# AGENTS.md\n\nMine, above.\n\n{inner}\n\nMine, below.\n")
    }

    #[test]
    fn render_then_find_returns_the_same_body() {
        let text = host(&render("gates", GATES));
        let got = find(&text, "gates").unwrap().expect("a block");
        assert_eq!(got.body, GATES);
        assert_eq!(got.name, "gates");
    }

    #[test]
    fn replacing_twice_is_byte_identical() {
        let once = replace(&host(&render("gates", "old")), "gates", GATES).unwrap();
        let twice = replace(&once, "gates", GATES).unwrap();
        assert_eq!(
            once, twice,
            "a second write of the same body must change nothing"
        );
    }

    #[test]
    fn content_outside_the_fence_is_never_touched() {
        let out = replace(&host(&render("gates", "old")), "gates", GATES).unwrap();
        assert!(out.starts_with("# AGENTS.md\n\nMine, above.\n"));
        assert!(out.ends_with("Mine, below.\n"));
    }

    #[test]
    fn a_file_without_markers_is_refused_rather_than_appended_to() {
        let plain = "# AGENTS.md\n\nAll mine.\n";
        let err = replace(plain, "gates", GATES).unwrap_err();
        assert!(matches!(err, MarkerError::Absent { .. }));
        assert!(
            find(plain, "gates").unwrap().is_none(),
            "absence reads as None"
        );
    }

    #[test]
    fn two_blocks_of_one_name_are_refused_naming_both_lines() {
        let text = format!("{}\n{}", render("gates", "a"), render("gates", "b"));
        match find(&text, "gates").unwrap_err() {
            MarkerError::Duplicate { first, second, .. } => {
                assert_eq!((first, second), (1, 4));
            }
            other => panic!("expected Duplicate, got {other:?}"),
        }
    }

    #[test]
    fn an_unterminated_block_is_refused_naming_its_line() {
        let text = format!("intro\n{}\nstill mine\n", begin("gates"));
        match find(&text, "gates").unwrap_err() {
            MarkerError::Unterminated { line, .. } => assert_eq!(line, 2),
            other => panic!("expected Unterminated, got {other:?}"),
        }
    }

    #[test]
    fn a_body_carrying_the_end_marker_is_refused() {
        let poisoned = format!("text\n{}\nmore", end("gates"));
        assert!(matches!(
            replace(&host(&render("gates", "old")), "gates", &poisoned),
            Err(MarkerError::BodyContainsEnd { .. })
        ));
    }

    #[test]
    fn a_marker_mentioned_mid_sentence_is_not_a_marker() {
        let text = format!("We write {} around it.\n", begin("gates"));
        assert!(find(&text, "gates").unwrap().is_none());
    }

    #[test]
    fn the_block_says_it_is_generated_and_by_what() {
        let rendered = render("gates", GATES);
        let first = rendered.lines().next().unwrap();
        assert!(
            first.contains("Devplane"),
            "the block must name what generated it"
        );
        assert!(
            first.contains("overwritten"),
            "and say that edits inside are lost"
        );
        // and the notice must not leak into the body
        let text = host(&rendered);
        assert_eq!(find(&text, "gates").unwrap().unwrap().body, GATES);
    }

    /// A block without the notice must still be found.

    #[test]
    fn a_block_without_the_notice_is_still_found() {
        let old = format!("<!-- BEGIN {NS}gates -->\n{GATES}\n{}", end("gates"));
        assert_eq!(find(&host(&old), "gates").unwrap().unwrap().body, GATES);
    }

    #[test]
    fn a_foreign_namespace_is_not_ours() {
        let text = "<!-- BEGIN_TF_DOCS -->\nterraform\n<!-- END_TF_DOCS -->\n";
        assert!(find(text, "gates").unwrap().is_none());
    }

    #[test]
    fn an_empty_body_still_round_trips() {
        let text = host(&render("gates", ""));
        assert_eq!(find(&text, "gates").unwrap().expect("a block").body, "");
    }
}
